USE [master]
GO

/****** Object:  Database [ms_gateways]    Script Date: 8/17/2020 10:32:34 ******/
CREATE DATABASE [ms_gateways]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ms_gateways', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ms_gateways.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ms_gateways_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ms_gateways_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ms_gateways].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ms_gateways] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ms_gateways] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ms_gateways] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ms_gateways] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ms_gateways] SET ARITHABORT OFF 
GO

ALTER DATABASE [ms_gateways] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ms_gateways] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ms_gateways] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ms_gateways] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ms_gateways] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ms_gateways] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ms_gateways] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ms_gateways] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ms_gateways] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ms_gateways] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ms_gateways] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ms_gateways] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ms_gateways] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ms_gateways] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ms_gateways] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ms_gateways] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ms_gateways] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ms_gateways] SET RECOVERY FULL 
GO

ALTER DATABASE [ms_gateways] SET  MULTI_USER 
GO

ALTER DATABASE [ms_gateways] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ms_gateways] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ms_gateways] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ms_gateways] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ms_gateways] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ms_gateways] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ms_gateways] SET  READ_WRITE 
GO


