USE [ms_gateways]
GO

CREATE TABLE [dbo].[gateway](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[serial_number] [nvarchar](50) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[ipv4] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_gateway] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


